-- Entrance file for neovim configuration
require("basic")
require("keybindings")
require("plugins")
require("colorscheme")
require("yank")

require("plugin-config.nvim-tree")
require("plugin-config.bufferline")
require("plugin-config.lualine")
require("plugin-config.telescope")
require("plugin-config.dashboard")
require("plugin-config.nvim-treesitter")
require("plugin-config.indent-blankline")
require("plugin-config.neoscroll")
require("plugin-config.nvim-scrollview")
require("plugin-config.autopairs")
require("plugin-config.comment")
require("plugin-config.surround")
require("plugin-config.undotree")
require("plugin-config.markdown-preview")
require("plugin-config.hop")
require("plugin-config.symbols-outline")
require("plugin-config.flutter-tools")
require("plugin-config.todo-comments")
require("plugin-config.transparent")

require("lsp.setup")
require("lsp.cmp")
require("lsp.ui")
require("lsp.null-ls")
